language: r
cache: packages

matrix:
    include:
        - r: release
          after_success:
              - Rscript -e "covr::codecov()"
        - r: devel
        - r: oldrel
        - os: osx
          r: release
    allow_failures:
        - os: osx
          r: release

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

notifications:
  email:
    on_success: change
    on_failure: change

r_packages: covr
