language: r
cache: packages

matrix:
    include:
        - r: oldrel
          os: linux
          dist: trusty # 14.04
        - r: release
          os: linux
          dist: trusty
          env: R_CODECOV=true
        - r: devel
          os: linux
          dist: trusty
        - r: oldrel
          os: osx
        - r: release
          os: osx
          #- r: devel
          #os: osx

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

notifications:
  email:
    on_success: change
    on_failure: change

r_packages: covr

after_success:
      - Rscript -e 'covr::codecov()'
